# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del alumno')),
                ('apellidoPaterno', models.CharField(max_length=60, verbose_name='Primer apellido')),
                ('apellidoMaterno', models.CharField(max_length=60, verbose_name='Segundo apellido')),
                ('matricula', models.IntegerField(verbose_name='Ingresa matricula')),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
